version: '3.9'

services:

  mongo:
    container_name: T_mongo
    image: mongo:7.0

    ports:
      - "27017:27017"

  redis:
    container_name: T_redis
    image: redis:6.0

    ports:
      - "6379:6379"

  app:
    build: .

    container_name: T_app

    ports:
      - "80:80"

    volumes:
      - .:/app

    environment:
      # General
      FLASK_ENV: "development"
      SERVICE_NAME: "app-template"
      ENVIRONMENT: "development"
      SECRET_TOKEN: "secret-token"
      SERVER_URL: "http://localhost:5000"
      ELASTIC_APM_ENABLED: "false"

      # MongoDB and Redis
      MONGO_URL: "mongo"
      REDIS_HOST: "redis"

    depends_on:
      - mongo
      - redis
